/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_eclipse_serializer_nativememory_NativeMemoryAccessor */

#ifndef _Included_org_eclipse_serializer_nativememory_NativeMemoryAccessor
#define _Included_org_eclipse_serializer_nativememory_NativeMemoryAccessor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_eclipse_serializer_nativememory_NativeMemoryAccessor
 * Method:    getDirectByteBufferAddress
 * Signature: (Ljava/nio/ByteBuffer;)J
 */
JNIEXPORT jlong JNICALL Java_org_eclipse_serializer_nativememory_NativeMemoryAccessor_getDirectByteBufferAddress
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_eclipse_serializer_nativememory_NativeMemoryAccessor
 * Method:    allocateMemory
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_eclipse_serializer_nativememory_NativeMemoryAccessor_allocateMemory
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_eclipse_serializer_nativememory_NativeMemoryAccessor
 * Method:    reallocateMemory
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_eclipse_serializer_nativememory_NativeMemoryAccessor_reallocateMemory
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_eclipse_serializer_nativememory_NativeMemoryAccessor
 * Method:    freeMemory
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_eclipse_serializer_nativememory_NativeMemoryAccessor_freeMemory
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_eclipse_serializer_nativememory_NativeMemoryAccessor
 * Method:    fillMemory
 * Signature: (JJB)V
 */
JNIEXPORT void JNICALL Java_org_eclipse_serializer_nativememory_NativeMemoryAccessor_fillMemory
  (JNIEnv *, jobject, jlong, jlong, jbyte);

/*
 * Class:     org_eclipse_serializer_nativememory_NativeMemoryAccessor
 * Method:    get_byte
 * Signature: (J)B
 */
JNIEXPORT jbyte JNICALL Java_org_eclipse_serializer_nativememory_NativeMemoryAccessor_get_1byte__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_eclipse_serializer_nativememory_NativeMemoryAccessor
 * Method:    get_boolean
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_eclipse_serializer_nativememory_NativeMemoryAccessor_get_1boolean__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_eclipse_serializer_nativememory_NativeMemoryAccessor
 * Method:    get_short
 * Signature: (J)S
 */
JNIEXPORT jshort JNICALL Java_org_eclipse_serializer_nativememory_NativeMemoryAccessor_get_1short__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_eclipse_serializer_nativememory_NativeMemoryAccessor
 * Method:    get_char
 * Signature: (J)C
 */
JNIEXPORT jchar JNICALL Java_org_eclipse_serializer_nativememory_NativeMemoryAccessor_get_1char__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_eclipse_serializer_nativememory_NativeMemoryAccessor
 * Method:    get_int
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_eclipse_serializer_nativememory_NativeMemoryAccessor_get_1int__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_eclipse_serializer_nativememory_NativeMemoryAccessor
 * Method:    get_float
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_eclipse_serializer_nativememory_NativeMemoryAccessor_get_1float__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_eclipse_serializer_nativememory_NativeMemoryAccessor
 * Method:    get_long
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_eclipse_serializer_nativememory_NativeMemoryAccessor_get_1long__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_eclipse_serializer_nativememory_NativeMemoryAccessor
 * Method:    get_double
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_org_eclipse_serializer_nativememory_NativeMemoryAccessor_get_1double__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_eclipse_serializer_nativememory_NativeMemoryAccessor
 * Method:    get_byte
 * Signature: (Ljava/lang/Object;J)B
 */
JNIEXPORT jbyte JNICALL Java_org_eclipse_serializer_nativememory_NativeMemoryAccessor_get_1byte__Ljava_lang_Object_2J
  (JNIEnv *, jobject, jobject, jlong);

/*
 * Class:     org_eclipse_serializer_nativememory_NativeMemoryAccessor
 * Method:    get_boolean
 * Signature: (Ljava/lang/Object;J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_eclipse_serializer_nativememory_NativeMemoryAccessor_get_1boolean__Ljava_lang_Object_2J
  (JNIEnv *, jobject, jobject, jlong);

/*
 * Class:     org_eclipse_serializer_nativememory_NativeMemoryAccessor
 * Method:    get_short
 * Signature: (Ljava/lang/Object;J)S
 */
JNIEXPORT jshort JNICALL Java_org_eclipse_serializer_nativememory_NativeMemoryAccessor_get_1short__Ljava_lang_Object_2J
  (JNIEnv *, jobject, jobject, jlong);

/*
 * Class:     org_eclipse_serializer_nativememory_NativeMemoryAccessor
 * Method:    get_char
 * Signature: (Ljava/lang/Object;J)C
 */
JNIEXPORT jchar JNICALL Java_org_eclipse_serializer_nativememory_NativeMemoryAccessor_get_1char__Ljava_lang_Object_2J
  (JNIEnv *, jobject, jobject, jlong);

/*
 * Class:     org_eclipse_serializer_nativememory_NativeMemoryAccessor
 * Method:    get_int
 * Signature: (Ljava/lang/Object;J)I
 */
JNIEXPORT jint JNICALL Java_org_eclipse_serializer_nativememory_NativeMemoryAccessor_get_1int__Ljava_lang_Object_2J
  (JNIEnv *, jobject, jobject, jlong);

/*
 * Class:     org_eclipse_serializer_nativememory_NativeMemoryAccessor
 * Method:    get_float
 * Signature: (Ljava/lang/Object;J)F
 */
JNIEXPORT jfloat JNICALL Java_org_eclipse_serializer_nativememory_NativeMemoryAccessor_get_1float__Ljava_lang_Object_2J
  (JNIEnv *, jobject, jobject, jlong);

/*
 * Class:     org_eclipse_serializer_nativememory_NativeMemoryAccessor
 * Method:    get_long
 * Signature: (Ljava/lang/Object;J)J
 */
JNIEXPORT jlong JNICALL Java_org_eclipse_serializer_nativememory_NativeMemoryAccessor_get_1long__Ljava_lang_Object_2J
  (JNIEnv *, jobject, jobject, jlong);

/*
 * Class:     org_eclipse_serializer_nativememory_NativeMemoryAccessor
 * Method:    get_double
 * Signature: (Ljava/lang/Object;J)D
 */
JNIEXPORT jdouble JNICALL Java_org_eclipse_serializer_nativememory_NativeMemoryAccessor_get_1double__Ljava_lang_Object_2J
  (JNIEnv *, jobject, jobject, jlong);

/*
 * Class:     org_eclipse_serializer_nativememory_NativeMemoryAccessor
 * Method:    getObject
 * Signature: (Ljava/lang/Object;J)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_org_eclipse_serializer_nativememory_NativeMemoryAccessor_getObject
  (JNIEnv *, jobject, jobject, jlong);

/*
 * Class:     org_eclipse_serializer_nativememory_NativeMemoryAccessor
 * Method:    set_byte
 * Signature: (JB)V
 */
JNIEXPORT void JNICALL Java_org_eclipse_serializer_nativememory_NativeMemoryAccessor_set_1byte__JB
  (JNIEnv *, jobject, jlong, jbyte);

/*
 * Class:     org_eclipse_serializer_nativememory_NativeMemoryAccessor
 * Method:    set_boolean
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_org_eclipse_serializer_nativememory_NativeMemoryAccessor_set_1boolean__JZ
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     org_eclipse_serializer_nativememory_NativeMemoryAccessor
 * Method:    set_short
 * Signature: (JS)V
 */
JNIEXPORT void JNICALL Java_org_eclipse_serializer_nativememory_NativeMemoryAccessor_set_1short__JS
  (JNIEnv *, jobject, jlong, jshort);

/*
 * Class:     org_eclipse_serializer_nativememory_NativeMemoryAccessor
 * Method:    set_char
 * Signature: (JC)V
 */
JNIEXPORT void JNICALL Java_org_eclipse_serializer_nativememory_NativeMemoryAccessor_set_1char__JC
  (JNIEnv *, jobject, jlong, jchar);

/*
 * Class:     org_eclipse_serializer_nativememory_NativeMemoryAccessor
 * Method:    set_int
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_eclipse_serializer_nativememory_NativeMemoryAccessor_set_1int__JI
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_eclipse_serializer_nativememory_NativeMemoryAccessor
 * Method:    set_float
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_org_eclipse_serializer_nativememory_NativeMemoryAccessor_set_1float__JF
  (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     org_eclipse_serializer_nativememory_NativeMemoryAccessor
 * Method:    set_long
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_eclipse_serializer_nativememory_NativeMemoryAccessor_set_1long__JJ
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_eclipse_serializer_nativememory_NativeMemoryAccessor
 * Method:    set_double
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_org_eclipse_serializer_nativememory_NativeMemoryAccessor_set_1double__JD
  (JNIEnv *, jobject, jlong, jdouble);

/*
 * Class:     org_eclipse_serializer_nativememory_NativeMemoryAccessor
 * Method:    set_byte
 * Signature: (Ljava/lang/Object;JB)V
 */
JNIEXPORT void JNICALL Java_org_eclipse_serializer_nativememory_NativeMemoryAccessor_set_1byte__Ljava_lang_Object_2JB
  (JNIEnv *, jobject, jobject, jlong, jbyte);

/*
 * Class:     org_eclipse_serializer_nativememory_NativeMemoryAccessor
 * Method:    set_boolean
 * Signature: (Ljava/lang/Object;JZ)V
 */
JNIEXPORT void JNICALL Java_org_eclipse_serializer_nativememory_NativeMemoryAccessor_set_1boolean__Ljava_lang_Object_2JZ
  (JNIEnv *, jobject, jobject, jlong, jboolean);

/*
 * Class:     org_eclipse_serializer_nativememory_NativeMemoryAccessor
 * Method:    set_short
 * Signature: (Ljava/lang/Object;JS)V
 */
JNIEXPORT void JNICALL Java_org_eclipse_serializer_nativememory_NativeMemoryAccessor_set_1short__Ljava_lang_Object_2JS
  (JNIEnv *, jobject, jobject, jlong, jshort);

/*
 * Class:     org_eclipse_serializer_nativememory_NativeMemoryAccessor
 * Method:    set_char
 * Signature: (Ljava/lang/Object;JC)V
 */
JNIEXPORT void JNICALL Java_org_eclipse_serializer_nativememory_NativeMemoryAccessor_set_1char__Ljava_lang_Object_2JC
  (JNIEnv *, jobject, jobject, jlong, jchar);

/*
 * Class:     org_eclipse_serializer_nativememory_NativeMemoryAccessor
 * Method:    set_int
 * Signature: (Ljava/lang/Object;JI)V
 */
JNIEXPORT void JNICALL Java_org_eclipse_serializer_nativememory_NativeMemoryAccessor_set_1int__Ljava_lang_Object_2JI
  (JNIEnv *, jobject, jobject, jlong, jint);

/*
 * Class:     org_eclipse_serializer_nativememory_NativeMemoryAccessor
 * Method:    set_float
 * Signature: (Ljava/lang/Object;JF)V
 */
JNIEXPORT void JNICALL Java_org_eclipse_serializer_nativememory_NativeMemoryAccessor_set_1float__Ljava_lang_Object_2JF
  (JNIEnv *, jobject, jobject, jlong, jfloat);

/*
 * Class:     org_eclipse_serializer_nativememory_NativeMemoryAccessor
 * Method:    set_long
 * Signature: (Ljava/lang/Object;JJ)V
 */
JNIEXPORT void JNICALL Java_org_eclipse_serializer_nativememory_NativeMemoryAccessor_set_1long__Ljava_lang_Object_2JJ
  (JNIEnv *, jobject, jobject, jlong, jlong);

/*
 * Class:     org_eclipse_serializer_nativememory_NativeMemoryAccessor
 * Method:    set_double
 * Signature: (Ljava/lang/Object;JD)V
 */
JNIEXPORT void JNICALL Java_org_eclipse_serializer_nativememory_NativeMemoryAccessor_set_1double__Ljava_lang_Object_2JD
  (JNIEnv *, jobject, jobject, jlong, jdouble);

/*
 * Class:     org_eclipse_serializer_nativememory_NativeMemoryAccessor
 * Method:    setObject
 * Signature: (Ljava/lang/Object;JLjava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_org_eclipse_serializer_nativememory_NativeMemoryAccessor_setObject
  (JNIEnv *, jobject, jobject, jlong, jobject);

/*
 * Class:     org_eclipse_serializer_nativememory_NativeMemoryAccessor
 * Method:    objectFieldOffset
 * Signature: (Ljava/lang/reflect/Field;)J
 */
JNIEXPORT jlong JNICALL Java_org_eclipse_serializer_nativememory_NativeMemoryAccessor_objectFieldOffset
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
