name: Make branch snapshot and deploy

on:
  push:
    branches-ignore:
      - main
      - 'release/**'

jobs:
  build-native:
    uses: ./.github/workflows/maven_jni_25.yml

  publish:
    if: github.repository == 'eclipse-serializer/serializer'
    runs-on: ubuntu-latest
    needs: build-native
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java 25 for publishing
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: 'maven'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

      - name: Download all native artifacts
        uses: actions/download-artifact@v4
        with:
          path: nativememory/target/libs
          merge-multiple: 'true'

      - name: Prepare suffix
        run: |
          suffix=$(echo -n "${GITHUB_REF#refs/heads/}" | tr '/' '_' | cut -c1-10)-$(echo -n "${GITHUB_REF#refs/heads/}" | md5sum | cut -c1-10)
          echo "Suffix: $suffix"
          echo "SUFFIX=$suffix" >> $GITHUB_ENV

      - name: Update project version
        run: |
          currentVersion=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
          newVersion="${currentVersion%-SNAPSHOT}-$SUFFIX-SNAPSHOT"
          mvn versions:set -DnewVersion=$newVersion --batch-mode

      - name: Deploy everything in one shot
        run: mvn -Pdeploy -P '!native-build' --no-transfer-progress --batch-mode clean deploy -Dmaven.javadoc.skip=true -Dgpg.skip=true
        env:
          MAVEN_USERNAME: ${{ secrets.CENTRAL_SONATYPE_TOKEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.CENTRAL_SONATYPE_TOKEN_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.ORG_GPG_PASSPHRASE }}
          MAVEN_GPG_KEY: ${{ secrets.ORG_GPG_PRIVATE_KEY }}

